#ifndef BOARD_DEFINES__H
#define BOARD_DEFINES__H

#ifndef LED_WHITE_PIN
    #define LED_WHITE_PIN 13
#endif //LED_WHITE_PIN

#ifndef LED_YELLOW_PIN
    #define LED_YELLOW_PIN 14
#endif //LED_YELLOW_PIN

#ifndef LED_GREEN_PIN
    #define LED_GREEN_PIN 15
#endif //LED_GREEN_PIN

#define LED_PINS {LED_WHITE_PIN, LED_YELLOW_PIN, LED_GREEN_PIN}
#define NUM_OF_LEDS 3


#endif //BOARD_DEFINES__H
